# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @authormaster
#  * EdgeX Foundry, Fuji, version master
#  * added: Jun 30, 2019
#  *******************************************************************************/

version: '3.4'

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  edgex_registry: consul://edgex-core-consul:8500
  Clients_CoreData_Host: edgex-core-data
  Clients_Logging_Host: edgex-support-logging
  Logging_EnableRemote: "true"
  Databases_Primary_Type: mongodb
  Databases_Primary_Host: edgex-mongo
  Databases_Primary_Port: 27017
  support-logging_Writable_Persistence: database

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  consul-scripts:
  vault-init:
  vault-config:
  vault-file:
  vault-logs:
  # non-shared volumes
  portainer_data:
  secrets-setup-cache:

services:
  volume:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-volume:master
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db:z
      - log-data:/edgex/logs:z
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z

  consul:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-consul:master
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    environment:
      - "SECRETSTORE_SETUP_DONE_FLAG=/tmp/edgex/secrets/edgex-consul/.secretstore-setup-done"
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
      - consul-scripts:/consul/scripts:z
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-consul:/tmp/edgex/secrets/edgex-consul:ro,z
      - /tmp/edgex/secrets/edgex-vault:/tmp/edgex/secrets/edgex-vault:ro,z
      - /tmp/edgex/secrets/edgex-kong:/tmp/edgex/secrets/edgex-kong:ro,z
    depends_on:
      - volume

  config-seed:
    image: nexus3.edgexfoundry.org:10004/docker-core-config-seed-go:master
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    environment:
      <<: *common-variables
    volumes:
      - db-data:/data/db:z
      - log-data:/edgex/logs:z
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    depends_on:
      - volume
      - consul

  vault:
    image: vault:1.3.1
    container_name: edgex-vault
    hostname: edgex-vault
    networks:
      edgex-network:
        aliases:
            - edgex-vault
    cap_add:
      - "IPC_LOCK"
    tmpfs:
      - /vault/config
    entrypoint: ["/vault/init/start_vault.sh"]
    environment:
      - VAULT_ADDR=https://edgex-vault:8200
      - VAULT_CONFIG_DIR=/vault/config
      - VAULT_UI=true
    volumes:
      - vault-file:/vault/file:z
      - vault-logs:/vault/logs:z
      - vault-init:/vault/init:ro,z
      - /tmp/edgex/secrets/edgex-vault:/tmp/edgex/secrets/edgex-vault:ro,z
    depends_on:
      - security-secrets-setup
      - consul

  security-secrets-setup:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-secrets-setup-go:master
    container_name: edgex-secrets-setup
    hostname: edgex-secrets-setup
    tmpfs:
      - /tmp
      - /run
    command: "generate"
    volumes:
      - secrets-setup-cache:/etc/edgex/pki
      - vault-init:/vault/init:z
      - /tmp/edgex/secrets:/tmp/edgex/secrets:z
    depends_on:
      - volume

  vault-worker:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:master
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    environment:
      - "SECRETSTORE_SETUP_DONE_FLAG=/tmp/edgex/secrets/edgex-consul/.secretstore-setup-done"
    networks:
      edgex-network:
        aliases:
            - edgex-vault-worker
    tmpfs:
      - /run
    volumes:
      - vault-config:/vault/config:z
      - consul-scripts:/consul/scripts:ro,z
      - /tmp/edgex/secrets:/tmp/edgex/secrets:z
    depends_on:
      - volume
      - consul
      - vault

# containers for reverse proxy
  kong-db:
    image: postgres:12.1-alpine
    container_name: kong-db
    hostname: kong-db
    networks:
      edgex-network:
        aliases:
            - kong-db
    environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'
        - 'POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'

  kong-migrations:
    image: kong:${KONG_VERSION:-2.0.1}
    container_name: kong-migrations
    networks:
      edgex-network:
        aliases:
            - kong-migrations
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
        - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
    command: >
      /bin/sh -cx 
      'until /consul/scripts/consul-svc-healthy.sh kong-db;
         do sleep 1;
      done && kong migrations bootstrap;
      kong migrations list;
      code=$$?;
      if [ $$code -eq 5 ]; then
        kong migrations up && kong migrations finish;
      fi'
    volumes:
      - consul-scripts:/consul/scripts:ro,z
    depends_on:
      - kong-db
      - volume
      - consul

  kong:
    image: kong:${KONG_VERSION:-2.0.1}
    container_name: kong
    hostname: kong
    networks:
      edgex-network:
        aliases:
            - kong
    ports:
        - "8000:8000"
        - "${KONG_BINDABLE_IP:-127.0.0.1}:8001:8001"
        - "8443:8443"
        - "${KONG_BINDABLE_IP:-127.0.0.1}:8444:8444"
    tty: true
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
        - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
        - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
        - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
        - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
    restart: on-failure
    command: >
      /bin/sh -c 
      "until /consul/scripts/consul-svc-healthy.sh kong-migrations; do sleep 1; done;
      /docker-entrypoint.sh kong docker-start"
    volumes:
      - consul-scripts:/consul/scripts:ro,z
    depends_on:
        - kong-db
        - kong-migrations
        - volume
        - consul

  edgex-proxy:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-proxy-setup-go:master
    container_name: edgex-proxy
    hostname: edgex-proxy
    entrypoint: >
      /bin/sh -c 
      "until /consul/scripts/consul-svc-healthy.sh kong; do sleep 1; done;
      until /consul/scripts/consul-svc-healthy.sh security-secretstore-setup; do sleep 1; done;
      /edgex/security-proxy-setup --init=true"
    networks:
      edgex-network:
        aliases:
            - edgex-proxy
    volumes:
      - consul-scripts:/consul/scripts:ro,z
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-security-proxy-setup:/tmp/edgex/secrets/edgex-security-proxy-setup:ro,z
    depends_on:
        - vault-worker
        - kong

# end of containers for reverse proxy

  mongo:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-mongo:master
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    entrypoint: >
      /bin/sh -c 
      "until /consul/scripts/consul-svc-healthy.sh security-secretstore-setup; do sleep 1; done;
      /edgex-mongo/bin/edgex-mongo-launch.sh"
    networks:
      - edgex-network
    volumes:
      - consul-scripts:/consul/scripts:ro,z
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-mongo:/tmp/edgex/secrets/edgex-mongo:ro,z
    depends_on:
      - volume
      - vault-worker

  logging:
    image: nexus3.edgexfoundry.org:10004/docker-support-logging-go:master
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs:z
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-support-logging:/tmp/edgex/secrets/edgex-support-logging:ro,z
    depends_on:
      - config-seed
      - mongo
      - volume

  system:
    image: nexus3.edgexfoundry.org:10004/docker-sys-mgmt-agent-go:master
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    depends_on:
      - logging

  notifications:
    image: nexus3.edgexfoundry.org:10004/docker-support-notifications-go:master
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-support-notifications:/tmp/edgex/secrets/edgex-support-notifications:ro,z
    depends_on:
      - logging

  metadata:
    image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:master
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-core-metadata:/tmp/edgex/secrets/edgex-core-metadata:ro,z
    depends_on:
      - logging

  data:
    image: nexus3.edgexfoundry.org:10004/docker-core-data-go:master
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-core-data:/tmp/edgex/secrets/edgex-core-data:ro,z
    depends_on:
      - logging

  command:
    image: nexus3.edgexfoundry.org:10004/docker-core-command-go:master
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-core-command:/tmp/edgex/secrets/edgex-core-command:ro,z
    depends_on:
      - metadata

  scheduler:
    image: nexus3.edgexfoundry.org:10004/docker-support-scheduler-go:master
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    volumes:
      - /tmp/edgex/secrets/ca:/tmp/edgex/secrets/ca:ro,z
      - /tmp/edgex/secrets/edgex-support-scheduler:/tmp/edgex/secrets/edgex-support-scheduler:ro,z
    depends_on:
      - metadata

  app-service-rules:
    image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master
    ports:
      - "48100:48100"
    container_name: edgex-app-service-configurable-rules
    hostname: edgex-app-service-configurable-rules
    entrypoint: ["/app-service-configurable"]
    command: ["--registry","--confdir=/res", "--skipVersionCheck=true"]
    networks:
      edgex-network:
        aliases:
          - edgex-app-service-configurable-rules
    environment:
      <<: *common-variables
      edgex_service: http://edgex-app-service-configurable-rules:48100
      edgex_profile: rules-engine
      Service_Host: edgex-app-service-configurable-rules
      MessageBus_SubscribeHost_Host: edgex-core-data
    depends_on:
      - consul
      - logging
      - data

  rulesengine:
    image: nexus3.edgexfoundry.org:10004/docker-support-rulesengine:master
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    networks:
      edgex-network:
        aliases:
          - edgex-support-rulesengine
    depends_on:
      - app-service-rules

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: nexus3.edgexfoundry.org:10004/docker-device-virtual-go:master
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    depends_on:
    - data
    - command

  # device-random:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-random-go:master
  #   ports:
  #     - "49988:49988"
  #   container_name: edgex-device-random
  #   hostname: edgex-device-random
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - log-data:/edgex/logs
  #   depends_on:
  #     - data
  #     - command
  #
  # device-mqtt:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-mqtt-go:master
  #   ports:
  #     - "49982:49982"
  #   container_name: edgex-device-mqtt
  #   hostname: edgex-device-mqtt
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - log-data:/edgex/logs
  #   depends_on:
  #     - data
  #     - command
  #
  # device-modbus:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-modbus-go:master
  #   ports:
  #     - "49991:49991"
  #   container_name: edgex-device-modbus
  #   hostname: edgex-device-modbus
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - log-data:/edgex/logs
  #   depends_on:
  #     - data
  #     - command
  #
  # device-snmp:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-snmp-go:master
  #   ports:
  #     - "49993:49993"
  #   container_name: edgex-device-snmp
  #   hostname: edgex-device-snmp
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - log-data:/edgex/logs
  #   depends_on:
  #     - data
  #     - command

#################################################################
# UIs
#################################################################
  ui:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-ui-go:master
    ports:
      - "4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    networks:
      - edgex-network
    depends_on:
      - data
      - command

#################################################################
# Tooling
#################################################################

  portainer:
    image:  portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - portainer_data:/data
    depends_on:
      - volume

networks:
  edgex-network:
    driver: "bridge"

