# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Fuji, version 1.1.0
#  * added: Jun 30, 2019
#  *******************************************************************************/

version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:
  vault-config:
  vault-file:
  vault-logs:
  secrets-setup-cache:

services:
  volume:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-volume:1.1.0
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  consul:
    image: consul:1.3.1
    ports:
      - "8400:8400"
      - "8500:8500"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    image: nexus3.edgexfoundry.org:10004/docker-core-config-seed-go:1.1.0
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul

  vault:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-secret-store-go:1.1.0
    container_name: edgex-vault
    hostname: edgex-vault
    networks:
      edgex-network:
        aliases:
            - edgex-vault
    ports:
      - "8200:8200"
    cap_add:
      - "IPC_LOCK"
    environment:
      - VAULT_ADDR=https://edgex-vault:8200
      - |
        VAULT_LOCAL_CONFIG=
          listener "tcp" { 
              tls_disable = "0" 
              cluster_address = "edgex-vault:8201" 
              tls_min_version = "tls12" 
              tls_client_ca_file ="/run/edgex/secrets/edgex-vault/ca.pem" 
              tls_cert_file ="/run/edgex/secrets/edgex-vault/server.crt" 
              tls_key_file = "/run/edgex/secrets/edgex-vault/server.key" 
              tls_perfer_server_cipher_suites = true 
          } 
          backend "consul" { 
              path = "vault/" 
              address = "edgex-core-consul:8500" 
              scheme = "http" 
              redirect_addr = "https://edgex-vault:8200" 
              cluster_addr = "https://edgex-vault:8201" 
          } 
          default_lease_ttl = "168h" 
          max_lease_ttl = "720h"
      - VAULT_CONFIG_DIR=/vault/config
      - VAULT_UI=true
    # create the tempfs directory inside the container for deployed purpose
    tmpfs:
      - /run/edgex/secrets/edgex-vault
    command: >
      /usr/bin/dumb-init -- /bin/sh -c 
      "./security-secrets-setup generate ;
      chown -Rh 100:1000 /run/edgex/secrets/edgex-vault/ ;
      exec /usr/local/bin/docker-entrypoint.sh server -log-level=info"
    volumes:
      - vault-file:/vault/file
      - vault-logs:/vault/logs
      - secrets-setup-cache:/etc/edgex/pki
      - vault-config:/vault/config
    depends_on:
      - volume
      - consul

  vault-worker:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-secretstore-setup-go:1.1.0
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    command: ["--init=true", "--vaultInterval=10", "--insecureSkipVerify=false"]
    networks:
      edgex-network:
        aliases:
            - edgex-vault-worker
    volumes:
      - vault-config:/vault/config
    depends_on:
      - volume
      - consul
      - vault

# containers for reverse proxy
  kong-db:
    image: "postgres:9.6"
    container_name: kong-db
    hostname: kong-db
    networks:
      edgex-network:
        aliases:
            - kong-db
    ports:
        - "5432:5432"
    environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'

  kong-migrations:
    image: "kong:1.0.3"
    container_name: kong-migration
    hostname: kong-migration
    networks:
      edgex-network:
        aliases:
            - kong-migration
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
    command: "kong migrations bootstrap"

  kong:
    image: "kong:1.0.3"
    container_name: kong
    hostname: kong
    networks:
      edgex-network:
        aliases:
            - kong
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8443:8443"
        - "8444:8444"
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
        - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
        - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
        - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
    depends_on:
        - kong-db

  edgex-proxy:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-security-proxy-setup-go:1.1.0
    container_name: edgex-proxy
    hostname: edgex-proxy
    command: ["--init=true", "--insecureSkipVerify=true"]
    networks:
      edgex-network:
        aliases:
            - edgex-proxy
    volumes:
        - vault-config:/vault/config
    depends_on:
        - vault
        - kong-db
        - kong

# end of containers for reverse proxy

  mongo:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-mongo:1.1.0
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - vault-config:/vault/config
    depends_on:
      - volume
      - vault-worker

  logging:
    image: nexus3.edgexfoundry.org:10004/docker-support-logging-go:1.1.0
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - config-seed
      - mongo
      - volume

  system:
    image: nexus3.edgexfoundry.org:10004/docker-sys-mgmt-agent-go:1.1.0
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logging

  notifications:
    image: nexus3.edgexfoundry.org:10004/docker-support-notifications-go:1.1.0
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  metadata:
    image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:1.1.0
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  data:
    image: nexus3.edgexfoundry.org:10004/docker-core-data-go:1.1.0
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging

  command:
    image: nexus3.edgexfoundry.org:10004/docker-core-command-go:1.1.0
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata

  scheduler:
    image: nexus3.edgexfoundry.org:10004/docker-support-scheduler-go:1.1.0
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata

  export-client:
    image: nexus3.edgexfoundry.org:10004/docker-export-client-go:1.1.0
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data

  export-distro:
    image: nexus3.edgexfoundry.org:10004/docker-export-distro-go:1.1.0
    ports:
      - "48070:48070"
      - "5566:5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none

  rulesengine:
    image: nexus3.edgexfoundry.org:10004/docker-support-rulesengine:1.1.0
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: nexus3.edgexfoundry.org:10004/docker-device-virtual-go:1.1.0
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - data
    - command

  # device-random:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-random-go:1.1.0
  #   ports:
  #     - "49988:49988"
  #   container_name: edgex-device-random
  #   hostname: edgex-device-random
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  # device-mqtt:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-mqtt-go:1.1.0
  #   ports:
  #     - "49982:49982"
  #   container_name: edgex-device-mqtt
  #   hostname: edgex-device-mqtt
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  # device-modbus:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-modbus-go:1.1.0
  #   ports:
  #     - "49991:49991"
  #   container_name: edgex-device-modbus
  #   hostname: edgex-device-modbus
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  # device-snmp:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-snmp-go:1.1.0
  #   ports:
  #     - "49993:49993"
  #   container_name: edgex-device-snmp
  #   hostname: edgex-device-snmp
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command

#################################################################
# UIs
#################################################################
  ui:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-ui-go:1.1.0
    ports:
      - "4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
      - command

#################################################################
# Tooling
#################################################################

  portainer:
    image:  portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    depends_on:
      - volume

networks:
  edgex-network:
    driver: "bridge"

