# /*******************************************************************************
#  * Copyright 2020 Redis Labs Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * @author: Andre Srinivasan, Redis Labs
#  * EdgeX Foundry, Geneva, version 1.2.0
#  * added: Feb 2020
#  *******************************************************************************/

# NOTE:  this Docker Compose file does not contain the security services - namely the API Gateway
# and Secret Store

version: '3.4'

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  Registry_Host: edgex-core-consul
  Clients_CoreData_Host: edgex-core-data
  Clients_Logging_Host: edgex-support-logging
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
  Clients_RulesEngine_Host: edgex-kuiper
  Clients_VirtualDevice_Host: edgex-device-virtual
  Databases_Primary_Type: mongodb
  Databases_Primary_Host: edgex-mongo
  Databases_Primary_Port: 27017

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

services:
  volume:
    image: ubuntu:latest
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db:z
      - log-data:/edgex/logs:z
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    entrypoint: [ "tail", "-f", "/dev/null" ]

  consul:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-consul:master
    ports:
      - "8400:8400"
      - "8500:8500"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    depends_on:
      - volume
    environment: 
      - EDGEX_DB=mongo
      - EDGEX_SECURE=false

  mongo:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-mongo:master
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      - db-data:/data/db:z
    depends_on:
      - volume

  logging:
    image: nexus3.edgexfoundry.org:10004/docker-support-logging-go:master
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-support-logging
      Writable_Persistence: database
      Logging_EnableRemote: "false"
      Logging_File: /edgex/logs/edgex-support-logging.log
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'logging'
    volumes:
      - log-data:/edgex/logs:z
    depends_on:
      - mongo
      - volume

  system:
    image: nexus3.edgexfoundry.org:10004/docker-sys-mgmt-agent-go:master
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-sys-mgmt-agent
      ExecutorPath: /sys-mgmt-executor
      MetricsMechanism: executor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    depends_on:
      - logging

  notifications:
    image: nexus3.edgexfoundry.org:10004/docker-support-notifications-go:master
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-support-notifications
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'notifications'
    depends_on:
      - logging

  metadata:
    image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:master
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-metadata
      Notifications_Sender: edgex-core-metadata
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'meta'
    depends_on:
      - logging

  data:
    image: nexus3.edgexfoundry.org:10004/docker-core-data-go:master
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-data
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'core'
    depends_on:
      - logging

  command:
    image: nexus3.edgexfoundry.org:10004/docker-core-command-go:master
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-core-command
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'meta'
    depends_on:
      - metadata

  scheduler:
    image: nexus3.edgexfoundry.org:10004/docker-support-scheduler-go:master
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    environment:
      <<: *common-variables
      Service_Host: edgex-support-scheduler
      IntervalActions_ScrubPushed_Host: edgex-core-data
      IntervalActions_ScrubAged_Host: edgex-core-data
      # TODO: Remove these when back in configuration.toml
      Databases_Primary_Password: 'password'
      Databases_Primary_Username: 'scheduler'
    depends_on:
      - metadata

  app-service-rules:
    image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable:master
    ports:
      - "48100:48100"
    container_name: edgex-app-service-configurable-rules
    hostname: edgex-app-service-configurable-rules
    entrypoint: ["/app-service-configurable"]
    command: ["--registry","--confdir=/res", "--skipVersionCheck=true"]
    networks:
      edgex-network:
        aliases:
          - edgex-app-service-configurable-rules
    environment:
      <<: *common-variables
      edgex_service: http://edgex-app-service-configurable-rules:48100
      edgex_profile: rules-engine
      Service_Host: edgex-app-service-configurable-rules
      edgex_registry: consul://edgex-core-consul:8500
      MessageBus_SubscribeHost_Host: edgex-core-data
      Binding_PublishTopic: events
    depends_on:
      - consul
      - logging
      - data
      
  rulesengine:
    image: emqx/kuiper:0.3.2
    ports:
      - "48075:48075"
      - "20498:20498"
    container_name: edgex-kuiper
    hostname: edgex-kuiper
    networks:
      edgex-network:
        aliases:
          - edgex-kuiper
    environment:
      # KUIPER_DEBUG: "true"
      KUIPER_CONSOLE_LOG: "true"
      KUIPER_REST_PORT: 48075
      EDGEX_SERVER: edgex-app-service-configurable-rules
      EDGEX_SERVICE_SERVER: http://edgex-core-data:48080
      EDGEX_TOPIC: events
      EDGEX_PROTOCOL: tcp
      EDGEX_PORT: 5566
    depends_on:
      - app-service-rules

  # rulesengine:
  #   image: nexus3.edgexfoundry.org:10004/docker-support-rulesengine:master
  #   ports:
  #     - "48075:48075"
  #   container_name: edgex-support-rulesengine
  #   hostname: edgex-support-rulesengine
  #   networks:
  #     edgex-network:
  #       aliases:
  #         - edgex-support-rulesengine
  #   depends_on:
  #     - app-service-rules

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: nexus3.edgexfoundry.org:10004/docker-device-virtual-go:master
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    environment:
      <<: *common-variables
      Service_Host: edgex-device-virtual
    depends_on:
    - data
    - command

  # device-random:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-random-go:master
  #   ports:
  #     - "49988:49988"
  #   container_name: edgex-device-random
  #   hostname: edgex-device-random
  #   networks:
  #     - edgex-network
  #      aliases:
  #      - edgex-device-random
  #   environment:
  #     <<: *common-variables
  #     Service_Host: edgex-device-random
  #   depends_on:
  #     - data
  #     - command
  #
  # device-mqtt:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-mqtt-go:master
  #   ports:
  #     - "49982:49982"
  #   container_name: edgex-device-mqtt
  #   hostname: edgex-device-mqtt
  #   networks:
  #     - edgex-network
  #      aliases:
  #      - edgex-device-mqtt
  #   environment:
  #     <<: *common-variables
  #     Service_Host: edgex-device-mqtt
  #   depends_on:
  #     - data
  #     - command
  #
  # device-modbus:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-modbus-go:master
  #   ports:
  #     - "49991:49991"
  #   container_name: edgex-device-modbus
  #   hostname: edgex-device-modbus
  #   networks:
  #     - edgex-network
  #      aliases:
  #      - edgex-device-modbus
  #   environment:
  #     <<: *common-variables
  #     Service_Host: edgex-device-modbus
  #   depends_on:
  #     - data
  #     - command
  #
  # device-snmp:
  #   image: nexus3.edgexfoundry.org:10004/docker-device-snmp-go:master
  #   ports:
  #     - "49993:49993"
  #   container_name: edgex-device-snmp
  #   hostname: edgex-device-snmp
  #   networks:
  #     - edgex-network
  #      aliases:
  #      - edgex-device-snmp
  #   environment:
  #     <<: *common-variables
  #     Service_Host: edgex-device-snmp
  #   depends_on:
  #     - data
  #     - command

#################################################################
# UIs
#################################################################
  ui:
    image: nexus3.edgexfoundry.org:10004/docker-edgex-ui-go:master
    ports:
      - "4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    networks:
      - edgex-network
    depends_on:
      - data
      - command

networks:
  edgex-network:
    driver: "bridge"

