# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Developer Docker Compose
#  * added: Feb 3, 2018
#  *******************************************************************************/

version: '3'

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

services:
  volume:
    image: edgexfoundry/docker-edgex-volume
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  config-seed:
    image: edgexfoundry/docker-core-config-seed
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:8600"
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed 
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  mongo:
    image: edgexfoundry/docker-edgex-mongo
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  logging:
    image: edgexfoundry/docker-support-logging
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo

  notifications:
    image: edgexfoundry/docker-support-notifications
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging

  metadata:
    image: edgexfoundry/docker-core-metadata
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging

  data:
    image: edgexfoundry/docker-core-data
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications

  command:
    image: edgexfoundry/docker-core-command
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata

  scheduler:
    image: edgexfoundry/docker-support-scheduler
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - command

  export-client:
    image: edgexfoundry/docker-export-client
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications
      - metadata
      - data

  export-distro:
    image: edgexfoundry/docker-export-distro
    ports:
      - "48070:48070"
      - "5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications
      - metadata
      - data
      - export-client

  rulesengine:
    image: edgexfoundry/docker-support-rulesengine
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - command
      - export-distro

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: edgexfoundry/docker-device-virtual
    ports:
      - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - data
      - command
      
  # device-bacnet:
    # image: edgexfoundry/docker-device-bacnet
    # ports:
      # - "49986:49986"
    # container_name: edgex-device-bacnet
    # hostname: edgex-device-bacnet
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-bluetooth:
    # image: edgexfoundry/docker-device-bluetooth
    # ports:
      # - "49988:49988"
    # container_name: edgex-device-bluetooth
    # hostname: edgex-device-bluetooth
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-fischertechnik:
    # image: edgexfoundry/docker-device-fischertechnik
    # ports:
      # - "49985:49985"
    # container_name: edgex-device-fischertechnik
    # hostname: edgex-device-fischertechnik
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-modbus:
    # image: edgexfoundry/docker-device-modbus
    # ports:
      # - "49991:49991"
    # container_name: edgex-device-modbus
    # hostname: edgex-device-modbus
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-mqtt:
    # image: edgexfoundry/docker-device-mqtt
    # ports:
      # - "49982:49982"
    # container_name: edgex-device-mqtt
    # hostname: edgex-device-mqtt
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-snmp:
    # image: edgexfoundry/docker-device-snmp
    # ports:
      # - "49989:49989"
    # container_name: edgex-device-snmp
    # hostname: edgex-device-snmp
    # networks:
      # - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
networks:
  edgex-network:
    driver: "bridge"
...
